# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 VEST
#

obj-y += vest_e2i_plus.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
ifdef CONFIG_IMX8M_LPDDR4_FREQ0_3200MTS
obj-y += lpddr4_timing_ndm.o
else
obj-$(CONFIG_IMX8M_LPDDR4) += lpddr4_timing.o
#obj-$(CONFIG_IMX8M_DDR4) += ddr4_timing.o
endif
endif
